name: Bump Git/Docker Version
on:
  push:
    branches:
      - master

jobs:
  semver:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tagging.outputs.new_tag }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.39.0
      id: tagging
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: master
        DEFAULT_BUMP: minor
  docker:
    runs-on: ubuntu-latest
    needs: semver
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
      - name: Build and push latest
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.repository }}:latest
      - name: Build and push versioned
        id: docker_build_versioned
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.repository }}:${{ needs.semver.outputs.tag }}
